name: TodoWorkflow
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo:4.4
        ports:
          - 27017:27017
          
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Dependencies for Backend
        run: |
          cd backend
          npm install

      - name: Install Dependencies for Frontend
        run: |
          cd frontend
          npm install

      - name: Start Server
        run: |
          cd backend
          npm run starttest &
        env:
          PORT: 3000

      - name: Wait for Server to be Ready
        run: |
          npx wait-on http://localhost:3000

      - name: Run Tests for Backend
        run: |
          cd backend
          npm test
          
      - name: Run Tests for Frontend
        run: |
          cd frontend
          npm test
  
