name: TodoWorkflow
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo:4.4
        ports:
          - 27017:27017

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Wait for MongoDB to be ready
        run: |
          for i in {1..10}; do
            if mongosh --eval "db.runCommand({ ping: 1 })"; then
              echo "MongoDB is ready";
              break;
            fi
            echo "Waiting for MongoDB...";
            sleep 5;
          done

      - name: Install Dependencies for Backend
        run: |
          cd backend
          npm install

      - name: Install Dependencies for Frontend
        run: |
          cd frontend
          npm install

      - name: Run Tests for Backend
        run: |
          cd backend
          npm test
          
      - name: Run Tests for Frontend
        run: |
          cd frontend
          npm test
  
